project:
  type: website
  output-dir: docs

website:
  title: "Gatins lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "People"
        file: people.qmd
      - text: "Research"
        file: research.qmd
      - text: "Molecular Protocols"
        file: molecularprotocols.qmd
        
  sidebar:
    - title: "Molecular Protocols"
      style: "docked"
      background: light
      contents:
        - molecularprotocols.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

