project:
  type: website
  output-dir: docs

website:
  title: "Gatins lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "People"
        file: people.qmd
      - text: "Research"
        file: research.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

