project:
  type: website
  output-dir: docs

website:
  title: "Gatins lab"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Welcome
#      - about.qmd
#      - people.qmd
#      - text: "Welcome"
#        file: welcome.qmd
      - text: "Lab Protocols"
        file: lab_generalprotocols.qmd
      - text: "Field Protocols"
        file: fieldprotocols.qmd
      - text: "Professional Development"
        file: prof_development.qmd

    right:
      - icon: github
        href: https://github.com/remygatins
      - icon: twitter 
        href: https://twitter.com/remygatins?lang=en
        
  sidebar:
    - title: "Welcome"
      logo: pictures/Gatins_Lab_logo_dark_small.png
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - section: "Welcome"
          contents: 
            - index.qmd
#           - welcome.qmd
            - welcome_onboarding.qmd
            
    - title: "Lab Protocols"
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - section: "General Protocols"
          contents: 
            - lab_generalprotocols.qmd
            - lab_gen_stableisotope.qmd
        - section: "Equipment"
          contents:
            - lab_equip_autoclave.qmd
            - lab_equip_tapestation.qmd
            - lab_equip_qubit.qmd
        - section: "Molecular Protocols"
          contents:
            - lab_molec_illuminalibraryprep.qmd
            - lab_molec_dnaextraction.qmd
            - lab_molec_DNA_beadcleanup.qmd
    
    - title: "Field Protocols"
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - section: "Fieldwork general"
          contents:
            - fieldprotocols.qmd
        - section: "Permits"
          contents:
            - field_permits_US.qmd
        - section: "Diving"
          contents: 
            - field_diving_general.qmd

    - title: "Professional Development"
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - section: "Professional Development"
          contents:
            - prof_development.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

