project:
  type: website
  output-dir: docs

website:
  title: "Gatins lab"
  navbar:
    background: primary
    search: true
#    left:
#      - href: index.qmd
#        text: Home
#      - about.qmd
#      - people.qmd
#      - text: "Welcome"
#        file: generalprotocols.qmd
#      - text: "General Protocols"
#        file: generalprotocols.qmd
#      - text: "Molecular Protocols"
#        file: molecularprotocols.qmd

    right:
      - icon: github
        href: https://github.com/remygatins
      - icon: twitter 
        href: https://twitter.com/remygatins?lang=en
        
  sidebar:
    - title: "Molecular Protocols"
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - section: "General Protocols"
          contents: 
            - generalprotocols.qmd
            - protocol_stableisotope.qmd
        - section: "Molecular Protocols"
          contents:
#            - molecularprotocols.qmd
            - molec_illuminalibraryprep.qmd
            - molec_dnaextraction.qmd
            - molec_DNA_beadcleanup.qmd
            
#    - title: "General Protocols"
#      contents:
#        - section: "General Protocols"
#          contents: 
#            - generalprotocols.qmd
#            - protocol_stableisotope.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

