project:
  type: website
  output-dir: docs

website:
  title: "Gatins lab"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Molecular Protocols"
        file: molecularprotocols.qmd
    right:
      - icon: github
        href: https://github.com/remygatins
      - icon: twitter 
        href: https://twitter.com/remygatins?lang=en
        
  sidebar:
    - title: "Molecular Protocols"
      style: "floating"
      background: light
      collapse-level: 1
    - section: "Molecular Protocols"
      contents:
        - molecularprotocols.qmd
        - molec_illuminalibraryprep.qmd
        - molec_dnaextraction.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

