project:
  type: website
  output-dir: docs

website:
  title: "Gatins lab"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
#      - about.qmd
#      - people.qmd
      - text: "Welcome"
        file: welcome.qmd
      - text: "Lab Protocols"
        file: generalprotocols.qmd
      - text: "Field Protocols"
        file: fieldprotocols.qmd

    right:
      - icon: github
        href: https://github.com/remygatins
      - icon: twitter 
        href: https://twitter.com/remygatins?lang=en
        
  sidebar:
    - title: "Welcome"
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - section: "Welcome"
          contents: 
            - welcome.qmd
            - welcome_gettingstarted.qmd
            - protocol_stableisotope.qmd
            
    - title: "Lab Protocols"
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - section: "General Protocols"
          contents: 
            - generalprotocols.qmd
            - protocol_stableisotope.qmd
        - section: "Equipment"
          contents:
            - general_equip_autoclave.qmd
            - general_equip_tapestation.qmd
            - general_equip_qubit.qmd
        - section: "Molecular Protocols"
          contents:
            - molecularprotocols.qmd
            - molec_illuminalibraryprep.qmd
            - molec_dnaextraction.qmd
            - molec_DNA_beadcleanup.qmd
    
    - title: "Field Protocols"
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - section: "Permits"
          contents:
            - fieldprotocols.qmd

        - section: "Diving"
          contents: 
            - field_diving_general.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

